# Generated by Django 4.2.7 on 2023-11-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order',
            name='ack_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='expected_delivery_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='issue_date',
            field=models.DateTimeField(null=True),
        ),
    ]
