# Generated by Django 4.2.7 on 2023-11-28 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_vendor_average_response_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase_order',
            old_name='issue_data',
            new_name='issue_date',
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('completed', 'completed'), ('canceled', 'canceled')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='vendor',
            field=models.ForeignKey(default=1984, on_delete=django.db.models.deletion.CASCADE, to='api.vendor'),
            preserve_default=False,
        ),
    ]
