# Generated by Django 4.2.7 on 2023-11-29 09:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_purchase_order_ack_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order',
            name='po_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
