# Generated by Django 4.2.7 on 2023-11-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_purchase_order_po_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='token',
            field=models.CharField(default=1, max_length=40, unique=True),
            preserve_default=False,
        ),
    ]
